### ISSUE TITLE
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libmediapipe_tasks_vision_jni.so" not found

### ISSUE THREAD

**Issue by cognoscloud** [shubham0204/OnDevice-Face-Recognition-Android#14]
Getting below error on physical device having android version 13 or 14
=========================
  E  FATAL EXCEPTION: main
                                                                                                    Process: com.ml.shubham0204.facenet_android, PID: 4776
                                                                                                    java.lang.NoClassDefFoundError: com.google.mediapipe.tasks.vision.facedetector.FaceDetector
                                                                                                    	at com.ml.shubham0204.facenet_android.domain.face_detection.MediapipeFaceDetector.<init>(MediapipeFaceDetector.kt:36)
                                                                                                    	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt.com_ml_shubham0204_facenet_android_di_AppModule$lambda$10$lambda$6(AppModuleGencom$ml$shubham0204$facenet_android$di.kt:16)
                                                                                                    	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt.$r8$lambda$GkfTTWW8vv1uCYMI6hEhwMZLxRs(Unknown Source:0)
                                                                                                    	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt$$ExternalSyntheticLambda8.invoke(D8$$SyntheticClass:0)
                                                                                                    	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
                                                                                                    	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                                                                                                    	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
                                                                                                    	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
                                                                                                    	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
                                                                                                    	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
                                                                                                    	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:109)
                                                                                                    	at org.koin.core.scope.Scope.resolveValue(Scope.kt:248)
                                                                                                    	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:234)
                                                                                                    	at org.koin.core.scope.Scope.get(Scope.kt:213)
                                                                                                    	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt.com_ml_shubham0204_facenet_android_di_AppModule$lambda$10$lambda$2(AppModuleGencom$ml$shubham0204$facenet_android$di.kt:26)
                                                                                                    	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt.$r8$lambda$Dve3zdBffP3z4D-UTMzc4njQsbU(Unknown Source:0)
                                                                                                    	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt$$ExternalSyntheticLambda4.invoke(D8$$SyntheticClass:0)
                                                                                                    	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
                                                                                                    	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                                                                                                    	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
                                                                                                    	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
                                                                                                    	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
                                                                                                    	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
                                                                                                    	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:109)
                                                                                                    	at org.koin.core.scope.Scope.resolveValue(Scope.kt:248)
                                                                                                    	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:234)
                                                                                                    	at org.koin.core.scope.Scope.get(Scope.kt:213)
                                                                                                    	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt.com_ml_shubham0204_facenet_android_di_AppModule$lambda$10$lambda$8(AppModuleGencom$ml$shubham0204$facenet_android$di.kt:56)
                                                                                                    	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt.$r8$lambda$I_ODvstVAn2_XLY-iMKuTXhJAFM(Unknown Source:0)
                                                                                                    	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt$$ExternalSyntheticLambda10.invoke(D8$$SyntheticClass:0)
                                                                                                    	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
                                                                                                    	at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
                                                                                                    	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:109)
                                                                                                    	at org.koin.core.scope.Scope.resolveValue(Scope.kt:248)
                                                                                                    	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:234)
                                                                                                    	at org.koin.core.scope.Scope.get(Scope.kt:213)
                                                                                                    	at org.koin.androidx.viewmodel.factory.KoinViewModelFactory.create(KoinViewModelFactory.kt:25)
                                                                                                    	at androidx.lifecycle.ViewModelProvider$Factory.create(ViewModelProvider.android.kt:158)
                                                                                                    	at androidx.lifecycle.viewmodel.ViewModelProviderImpl.getViewModel$lifecycle_viewmodel_release(ViewModelProviderImpl.kt:69)
2024-11-20 06:49:09.379  4776-4776  AndroidRuntime          pid-4776                             E  	at androidx.lifecycle.viewmodel.ViewModelProviderImpl.getViewModel$lifecycle_viewmodel_release$default(ViewModelProviderImpl.kt:47)
                                                                                                    	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.android.kt:91)
                                                                                                    	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.android.kt:109)
                                                                                                    	at org.koin.androidx.viewmodel.GetViewModelKt.resolveViewModel(GetViewModel.kt:44)
                                                                                                    	at com.ml.shubham0204.facenet_android.presentation.screens.detect_screen.DetectScreenKt.ScreenUI(DetectScreen.kt:221)
                                                                                                    	at com.ml.shubham0204.facenet_android.presentation.screens.detect_screen.DetectScreenKt.access$ScreenUI(DetectScreen.kt:1)
                                                                                                    	at com.ml.shubham0204.facenet_android.presentation.screens.detect_screen.ComposableSingletons$DetectScreenKt$lambda-4$1.invoke(DetectScreen.kt:100)
                                                                                                    	at com.ml.shubham0204.facenet_android.presentation.screens.detect_screen.ComposableSingletons$DetectScreenKt$lambda-4$1.invoke(DetectScreen.kt:99)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.material3.ScaffoldKt$ScaffoldLayoutWithMeasureFix$1$1$bodyContentPlaceables$1.invoke(Scaffold.kt:303)
                                                                                                    	at androidx.compose.material3.ScaffoldKt$ScaffoldLayoutWithMeasureFix$1$1$bodyContentPlaceables$1.invoke(Scaffold.kt:285)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$3$1$1.invoke(SubcomposeLayout.kt:991)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$3$1$1.invoke(SubcomposeLayout.kt:477)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:90)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3302)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3235)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:725)
                                                                                                    	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1071)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3599)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:633)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:619)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcomposeInto(SubcomposeLayout.kt:500)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:472)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:463)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:447)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:872)
                                                                                                    	at androidx.compose.material3.ScaffoldKt$ScaffoldLayoutWithMeasureFix$1$1.invoke-0kLqBqw(Scaffold.kt:285)
                                                                                                    	at androidx.compose.material3.ScaffoldKt$ScaffoldLayoutWithMeasureFix$1$1.invoke(Scaffold.kt:179)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:709)
                                                                                                    	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:126)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:252)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:251)
                                                                                                    	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:500)
2024-11-20 06:49:09.387  4776-4776  AndroidRuntime          pid-4776                             E  	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(MeasureAndLayoutDelegate.kt:354)
                                                                                                    	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureOnly(MeasureAndLayoutDelegate.kt:562)
                                                                                                    	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureOnly(MeasureAndLayoutDelegate.kt:407)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.onMeasure(AndroidComposeView.android.kt:1058)
                                                                                                    	at android.view.View.measure(View.java:28114)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView.internalOnMeasure$ui_release(ComposeView.android.kt:302)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView.onMeasure(ComposeView.android.kt:289)
                                                                                                    	at android.view.View.measure(View.java:28114)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                    	at android.view.View.measure(View.java:28114)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
                                                                                                    	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
                                                                                                    	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
                                                                                                    	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
                                                                                                    	at android.view.View.measure(View.java:28114)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                    	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:719)
                                                                                                    	at android.view.View.measure(View.java:28114)
                                                                                                    	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4823)
                                                                                                    	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3220)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3525)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2917)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10324)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:945)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8705)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
                                                                                                    Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libmediapipe_tasks_vision_jni.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1081)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1765)
                                                                                                    	at com.google.mediapipe.tasks.vision.facedetector.FaceDetector.<clinit>(FaceDetector.java:85)
                                                                                                    	at com.ml.shubham0204.facenet_android.domain.face_detection.MediapipeFaceDetector.<init>(MediapipeFaceDetector.kt:36)
                                                                                                    	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt.com_ml_shubham0204_facenet_android_di_AppModule$lambda$10$lambda$6(AppModuleGencom$ml$shubham0204$facenet_android$di.kt:16)
                                                                                                    	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt.$r8$lambda$GkfTTWW8vv1uCYMI6hEhwMZLxRs(Unknown Source:0)
                                                                                                    	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt$$ExternalSyntheticLambda8.invoke(D8$$SyntheticClass:0)
                                                                                                    	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
                                                                                                    	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                                                                                                    	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
                                                                                                    	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
2024-11-20 06:58:36.699  7115-7115  AndroidRuntime          pid-7115                             E  FATAL EXCEPTION: main
                                                                                                    Process: com.ml.shubham0204.facenet_android, PID: 7115
                                                                                                    java.lang.NoClassDefFoundError: com.google.mediapipe.tasks.vision.facedetector.FaceDetector
                                                                                                    	at com.ml.shubham0204.facenet_android.domain.face_detection.MediapipeFaceDetector.<init>(MediapipeFaceDetector.kt:36)
                                                                                                    	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt.com_ml_shubham0204_facenet_android_di_AppModule$lambda$10$lambda$6(AppModuleGencom$ml$shubham0204$facenet_android$di.kt:16)
                                                                                                    	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt.$r8$lambda$GkfTTWW8vv1uCYMI6hEhwMZLxRs(Unknown Source:0)
                                                                                                    	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt$$ExternalSyntheticLambda8.invoke(D8$$SyntheticClass:0)
                                                                                                    	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
                                                                                                    	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                                                                                                    	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)

**Comment by shubham0204** [comment]
Mediapipe has been removed from the project as a face detection service.
