### ISSUE TITLE
v0.0.1 APK error 

### ISSUE THREAD

**Issue by contigo** [shubham0204/OnDevice-Face-Recognition-Android#17]
E  FATAL EXCEPTION: main (Ask Gemini)
                                                               Process: com.ml.shubham0204.facenet_android, PID: 21214
                                                               java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                               	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:598)
                                                               	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                                                               Caused by: java.lang.reflect.InvocationTargetException
                                                               	at java.lang.reflect.Method.invoke(Native Method)
                                                               	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
                                                               	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 
                                                               Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for '[Factory:'com.ml.shubham0204.facenet_android.presentation.screens.detect_screen.DetectScreenViewModel']'
                                                               	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:57)
                                                               	at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
                                                               	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:109)
                                                               	at org.koin.core.scope.Scope.resolveValue(Scope.kt:248)
                                                               	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:234)
                                                               	at org.koin.core.scope.Scope.get(Scope.kt:213)
                                                               	at org.koin.androidx.viewmodel.factory.KoinViewModelFactory.create(KoinViewModelFactory.kt:25)
                                                               	at androidx.lifecycle.ViewModelProvider$Factory.create(ViewModelProvider.android.kt:158)
                                                               	at androidx.lifecycle.viewmodel.ViewModelProviderImpl.getViewModel$lifecycle_viewmodel_release(ViewModelProviderImpl.kt:67)
                                                               	at androidx.lifecycle.viewmodel.ViewModelProviderImpl.getViewModel$lifecycle_viewmodel_release$default(ViewModelProviderImpl.kt:47)
                                                               	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.android.kt:91)
                                                               	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.android.kt:109)
                                                               	at org.koin.androidx.viewmodel.GetViewModelKt.resolveViewModel(GetViewModel.kt:44)
                                                               	at com.ml.shubham0204.facenet_android.presentation.screens.detect_screen.DetectScreenKt.ScreenUI(DetectScreen.kt:221)
                                                               	at com.ml.shubham0204.facenet_android.presentation.screens.detect_screen.DetectScreenKt.access$ScreenUI(DetectScreen.kt:1)
                                                               	at com.ml.shubham0204.facenet_android.presentation.screens.detect_screen.ComposableSingletons$DetectScreenKt$lambda-4$1.invoke(DetectScreen.kt:100)
                                                               	at com.ml.shubham0204.facenet_android.presentation.screens.detect_screen.ComposableSingletons$DetectScreenKt$lambda-4$1.invoke(DetectScreen.kt:99)
                                                               	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
                                                               	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                               	at androidx.compose.material3.ScaffoldKt$ScaffoldLayoutWithMeasureFix$1$1$bodyContentPlaceables$1.invoke(Scaffold.kt:303)
                                                               	at androidx.compose.material3.ScaffoldKt$ScaffoldLayoutWithMeasureFix$1$1$bodyContentPlaceables$1.invoke(Scaffold.kt:285)
                                                               	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                               	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                               	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$3$1$1.invoke(SubcomposeLayout.kt:991)
                                                               	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$3$1$1.invoke(SubcomposeLayout.kt:477)
                                                               	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                               	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                               	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:90)
                                                               	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3302)
                                                               	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3235)
                                                               	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:725)
                                                               	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1071)
                                                               	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3599)
                                                               	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:633)
13:36:53.499 AndroidRuntime                                 E  	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:619) (Ask Gemini)
                                                               	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcomposeInto(SubcomposeLayout.kt:500)
                                                               	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:472)
                                                               	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:463)
                                                               	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:447)
                                                               	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:872)
                                                               	at androidx.compose.material3.ScaffoldKt$ScaffoldLayoutWithMeasureFix$1$1.invoke-0kLqBqw(Scaffold.kt:285)
                                                               	at androidx.compose.material3.ScaffoldKt$ScaffoldLayoutWithMeasureFix$1$1.invoke(Scaffold.kt:179)
                                                               	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:709)
                                                               	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:126)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:252)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:251)
                                                               	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
                                                               	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:500)
                                                               	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:256)
                                                               	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                                               	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:113)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:1617)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:36)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:620)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(LayoutNodeLayoutDelegate.kt:596)
                                                               	at androidx.compose.foundation.layout.BoxMeasurePolicy.measure-3p2s80s(Box.kt:122)
                                                               	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:126)
                                                               	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:646)
                                                               	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:116)
                                                               	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:646)
                                                               	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:116)
                                                               	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(Size.kt:699)
                                                               	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:116)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:252)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:251)
                                                               	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
                                                               	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:500)
                                                               	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:256)
                                                               	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                                               	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:113)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:1617)
13:36:53.499 AndroidRuntime                                 E  	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:36) (Ask Gemini)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:620)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(LayoutNodeLayoutDelegate.kt:596)
                                                               	at androidx.compose.animation.AnimatedEnterExitMeasurePolicy.measure-3p2s80s(AnimatedVisibility.kt:851)
                                                               	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:126)
                                                               	at androidx.compose.animation.EnterExitTransitionModifierNode.measure-3p2s80s(EnterExitTransition.kt:1156)
                                                               	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:116)
                                                               	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:646)
                                                               	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:116)
                                                               	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$1.invoke-3p2s80s(AnimatedContent.kt:733)
                                                               	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$1.invoke(AnimatedContent.kt:732)
                                                               	at androidx.compose.ui.layout.LayoutModifierImpl.measure-3p2s80s(LayoutModifier.kt:294)
                                                               	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:116)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:252)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:251)
                                                               	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
                                                               	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:500)
                                                               	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:256)
                                                               	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                                               	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:113)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:1617)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:36)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:620)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(LayoutNodeLayoutDelegate.kt:596)
                                                               	at androidx.compose.animation.AnimatedContentMeasurePolicy.measure-3p2s80s(AnimatedContent.kt:787)
                                                               	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:126)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:252)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:251)
                                                               	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
                                                               	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:500)
                                                               	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:256)
                                                               	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                                               	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:113)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:1617)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:36)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:620)
13:36:53.499 AndroidRuntime                                 E  	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(LayoutNodeLayoutDelegate.kt:596) (Ask Gemini)
                                                               	at androidx.compose.ui.layout.RootMeasurePolicy.measure-3p2s80s(RootMeasurePolicy.kt:38)
                                                               	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:126)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:252)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:251)
                                                               	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
                                                               	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:500)
                                                               	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:256)
                                                               	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                                               	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:113)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:1617)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:36)
                                                               	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:620)
                                                               	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(LayoutNode.kt:1145)
                                                               	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(MeasureAndLayoutDelegate.kt:354)
                                                               	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureOnly(MeasureAndLayoutDelegate.kt:562)
                                                               	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureOnly(MeasureAndLayoutDelegate.kt:407)
                                                               	at androidx.compose.ui.platform.AndroidComposeView.onMeasure(AndroidComposeView.android.kt:1058)
                                                               	at android.view.View.measure(View.java:28588)
                                                               	at androidx.compose.ui.platform.AbstractComposeView.internalOnMeasure$ui_release(ComposeView.android.kt:302)
                                                               	at androidx.compose.ui.platform.AbstractComposeView.onMeasure(ComposeView.android.kt:289)
                                                               	at android.view.View.measure(View.java:28588)
                                                               	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7442)
                                                               	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                               	at android.view.View.measure(View.java:28588)
                                                               	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7442)
                                                               	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
                                                               	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
                                                               	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
                                                               	at android.view.View.measure(View.java:28588)
                                                               	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7442)
                                                               	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                               	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1054)
                                                               	at android.view.View.measure(View.java:28588)
                                                               	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:5273)
                                                               	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3660)
                                                               	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4030)
                                                               	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3345)
                                                               	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11437)
                                                               	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1690)
                                                               	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1699)
                                                               	at android.view.Choreographer.doCallbacks(Choreographer.java:1154)
                                                               	at android.view.Choreographer.doFrame(Choreographer.java:1080)
                                                               	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1647)
                                                               	at android.os.Handler.handleCallback(Handler.java:958)
                                                               	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                               	at android.os.Looper.loopOnce(Looper.java:230)
                                                               	at android.os.Looper.loop(Looper.java:319)
                                                               	at android.app.ActivityThread.main(ActivityThread.java:9063)
                                                               	... 3 more
13:36:53.499 AndroidRuntime                                 E  Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for '[Singleton:'com.ml.shubham0204.facenet_android.domain.ImageVectorUseCase']' (Ask Gemini)
                                                               	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:57)
                                                               	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                                                               	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
                                                               	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
                                                               	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
                                                               	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
                                                               	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:109)
                                                               	at org.koin.core.scope.Scope.resolveValue(Scope.kt:248)
                                                               	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:234)
                                                               	at org.koin.core.scope.Scope.get(Scope.kt:213)
                                                               	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt.com_ml_shubham0204_facenet_android_di_AppModule$lambda$10$lambda$8(AppModuleGencom$ml$shubham0204$facenet_android$di.kt:56)
                                                               	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt.$r8$lambda$I_ODvstVAn2_XLY-iMKuTXhJAFM(Unknown Source:0)
                                                               	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt$$ExternalSyntheticLambda10.invoke(D8$$SyntheticClass:0)
                                                               	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
                                                               	... 158 more
                                                               Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for '[Singleton:'com.ml.shubham0204.facenet_android.domain.face_detection.FaceSpoofDetector']'
                                                               	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:57)
                                                               	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                                                               	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
                                                               	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
                                                               	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
                                                               	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
                                                               	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:109)
                                                               	at org.koin.core.scope.Scope.resolveValue(Scope.kt:248)
                                                               	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:234)
                                                               	at org.koin.core.scope.Scope.get(Scope.kt:213)
                                                               	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt.com_ml_shubham0204_facenet_android_di_AppModule$lambda$10$lambda$2(AppModuleGencom$ml$shubham0204$facenet_android$di.kt:26)
                                                               	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt.$r8$lambda$Dve3zdBffP3z4D-UTMzc4njQsbU(Unknown Source:0)
                                                               	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt$$ExternalSyntheticLambda4.invoke(D8$$SyntheticClass:0)
                                                               	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
                                                               	... 171 more
                                                               Caused by: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Failed to add NN API tensor: type INT64 is not supported.
                                                               Restored original execution plan after delegate application failure.
                                                               	at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
                                                               	at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:110)
                                                               	at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:73)
                                                               	at org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:36)
                                                               	at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:232)
                                                               	at com.ml.shubham0204.facenet_android.domain.face_detection.FaceSpoofDetector.<init>(FaceSpoofDetector.kt:70)
                                                               	at com.ml.shubham0204.facenet_android.domain.face_detection.FaceSpoofDetector.<init>(FaceSpoofDetector.kt:37)
13:36:53.499 AndroidRuntime                                 E  	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt.com_ml_shubham0204_facenet_android_di_AppModule$lambda$10$lambda$5(AppModuleGencom$ml$shubham0204$facenet_android$di.kt:15) (Ask Gemini)
                                                               	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt.$r8$lambda$MqHCb16ndpvheWgv3owyFRHosDw(Unknown Source:0)
                                                               	at org.koin.ksp.generated.AppModuleGencom_ml_shubham0204_facenet_android_diKt$$ExternalSyntheticLambda7.invoke(D8$$SyntheticClass:0)
                                                               	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
                                                               	... 184 more #

------------------------------------------------
 fold5 
OneUI 6.1.1 
android 14 

There were no problems with the apk installation 
An error occurs when running the app 
Added log

**Comment by shubham0204** [comment]
This is happening because Koin is not able to create an instance of `FaceSpoofDetector.kt`, which is one of the transitive dependencies of `DetectScreenViewModel.kt`. The error is:

```
Caused by: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Failed to add NN API tensor: type INT64 is not supported.
```

It seems that NNAPI does not support 64-bit architectures. I can find an [open issue](https://github.com/google-ai-edge/LiteRT/issues/149) on the LiteRT repository.

**Comment by shubham0204** [comment]
The new APK with NNAPI disabled by default is available as a [new release](https://github.com/shubham0204/OnDevice-Face-Recognition-Android/releases/tag/v0.0.1). 

Do let me know if it works correctly on your device, and we can close this issue.

**Comment by contigo** [comment]
fold 6 
Fold 5 

Installation and execution are both normal. 
thank you

**Comment by contigo** [comment]
Normal on LG V50(android 12)
